name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Shell script lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update || true
          sudo apt-get install -y shellcheck || true

      - name: Run ShellCheck on scripts
        run: |
          # Lint top-level scripts directory. Adjust glob if you keep scripts elsewhere.
          shellcheck -x scripts/*.sh

  build_iso:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y archiso squashfs-tools xorriso syslinux mtools rsync git || true

      - name: Run ISO build script
        run: |
          chmod +x scripts/build.sh
          sudo ./scripts/build.sh

      - name: Upload built ISO
        uses: actions/upload-artifact@v4
        with:
          name: asenos-iso
          # Update this path if your build script emits ISO to a different location
          path: out/*.iso
