name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Shell script lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update || true
          sudo apt-get install -y shellcheck || true

      - name: Run ShellCheck on scripts
        run: |
          # Lint top-level scripts directory. Adjust glob if you keep scripts elsewhere.
          shellcheck -x scripts/*.sh

  build_iso:
    name: Build ISO (Arch container)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO in Arch container
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            archlinux:latest \
            bash -c "
              # Update system and install dependencies
              pacman -Syu --noconfirm
              pacman -S --noconfirm archiso squashfs-tools xorriso syslinux mtools rsync git

              # Make build script executable and run it
              chmod +x scripts/build.sh
              ./scripts/build.sh
      - name: Upload built ISO
        uses: actions/upload-artifact@v4
        with:
          name: asenos-iso
          # Update this path if your build script emits ISO to a different location
          path: out/*.iso
