name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Shell script lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update || true
          sudo apt-get install -y shellcheck || true

      - name: Run ShellCheck on scripts
        run: |
          # Lint top-level scripts directory. Adjust glob if you keep scripts elsewhere.
          shellcheck -x scripts/*.sh
